### ISSUE TITLE
Updated Datafaker?

### ISSUE THREAD

**Issue by bodiam** [tigersoftdev/faker-intellij-plugin#12]
Hi there,

My name is Erik Pragt, and I'm one of the maintainers of Datafaker. Thanks for adding our library into this IntelliJ plugin, I had no idea about this, and this is so great, thank you for that!

I saw you are using a somewhat older version of Datafaker (1.2.0), and we're about to release a new version (1.7.0). 

Would you be interested in a PR which updates to the latest version of Datafaker?

Cheers,

Erik

**Comment by tigersoftdev** [comment]
Hi @bodiam!

Sure, feel free to add a PR with datafaker version update. When do you plan to release 1.7.0 version?

Thanks,
Michał

**Comment by bodiam** [comment]
Great, and thanks for your reaction! 

The plan is soon, hopefully within a week.

**Comment by xVemu** [comment]
Any news on this?

**Comment by tigersoftdev** [comment]
Hey @bodiam @xVemu new version will be released this week!

**Comment by bodiam** [comment]
Great! Just keep in mind that Datafaker 2.x is now a Java 17 library, I'm not sure if that's an issue or not.

**Comment by tigersoftdev** [comment]
Hi @bodiam,
I'm trying to update datafaker version to 1.9.0 (Java 8 is limiting here) but I'm having some weird issue. I can get plugin running with v1.6.0 but 1.7.0 onwards is not displaying Faker in context menu. Is there anything in my code that has to be adjusted to get it working with 1.9.0? Here's main code:
[link](https://github.com/tigersoftdev/faker-intellij-plugin/blob/master/src/main/java/pl/tigersoft/intellij/faker/actions/FakerActionGroup.java)
Thanks!

**Comment by bodiam** [comment]
Hi @tigersoftdev , that's a bit hard to say, I can't easily run that code since it's so integrated in the IntelliJ framework, but what I expect is the plugin isn't properly dealing with the new interfaces.

If you look at this:
https://github.com/datafaker-net/datafaker/blob/v1.6.0/src/main/java/net/datafaker/Faker.java
vs this:
https://github.com/datafaker-net/datafaker/blob/v1.7.0/src/main/java/net/datafaker/Faker.java

You can see that all of functionality has moved to the super interfaces, instead of being in Faker itself, so my guess is that this line is failing:

https://github.com/tigersoftdev/faker-intellij-plugin/blob/master/src/main/java/pl/tigersoft/intellij/faker/actions/FakerActionGroup.java#L40

Here you are using `getDeclaredMethods`, while I think you should be using `getMethods` instead. Also, the `.instance()` method of Faker has been removed; instead you can create a new instance of Faker, it's no longer expensive to instantiate a Faker object.

Hope that helps!

**Comment by bodiam** [comment]
Btw, IntelliJ seems to be using Java 17 these days: `Runtime version: 17.0.9+7-b1087.7 aarch64`

Any reason why you want to stay at Java 8?

**Comment by bodiam** [comment]
Hi @tigersoftdev , I've created a PR for this change here: https://github.com/tigersoftdev/faker-intellij-plugin/pull/13

It's not perfect, I had to disable the changelog and publish plugin, but it's now working for the latest IntelliJ version (I'd recommend using 2022.2 as the lowest minimal version, since that's the first Java 17 version, as indicated here: https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#platformVersions)

I hope you can finish this PR, and publish a new version. I've tried it, and it works fine:

<img width="668" alt="image" src="https://github.com/tigersoftdev/faker-intellij-plugin/assets/46468/aef4647a-46e8-446d-bedf-372a9566b176">

**Comment by tigersoftdev** [comment]
Hi @bodiam 
Thank you for your help and PR, I'm gonna review it shortly and try to release updated version of the plugin.
Regarding java 8 - just wanted to realease quicker with minimum effort but it looks like migration to java 17 will be necessary.

**Comment by tigersoftdev** [comment]
Hi @bodiam
I've decided to make this update with two phases - upgrade datafaker itself and later on bum up java version. Your PR is extremely helpful, I'm gonna use it again when upgrading java (and datafaker).
Feel free to upgrade Faker plugin to v1.3.0, it should be available for your Jet Brains IDE.
Thanks for help!
